### ISSUE TITLE
Apple M1 support

### ISSUE THREAD

**Issue by tizot** [techouse/alfred-tailwindcss-docs#2]
Hi,

The workflow unfortunately does not work on Apple MacBook M1.
When the script is executed, I see the message "Bad CPU type in executable". I guess this is due to the fact that it is compiled to a binary with Dart now.

**Comment by techouse** [comment]
Correct that is a [known limitation of the binary compilation process](https://dart.dev/tools/dart-compile#known-limitations).

> The exe subcommand has some known limitations:
>
> No cross-compilation support ([issue 28617](https://github.com/dart-lang/sdk/issues/28617))
> The compiler can create machine code only for the operating system on which you’re compiling. To create executables for > macOS, Windows, and Linux, you need to run the compiler three times. You can also use a continuous integration (CI) > provider that supports all three operating systems.

Unfortunately, I do not own an Apple M1 yet, so you have 2 options:

### Option A: Modify the workflow using the [Rosetta technique](https://medium.com/swlh/run-x86-terminal-apps-like-homebrew-on-your-new-m1-mac-73bdc9b0f343)

All you have to do is change the calling script command from

```bash
./docs -q "{query}"
```

to

```bash
arch -86_64 ./docs -q "{query}"
```

![Screenshot 2022-12-22 at 20 42 53](https://user-images.githubusercontent.com/1174328/209224015-e43f0276-ebd1-448d-bee8-ca977f2a14db.png)

![Screenshot 2022-12-22 at 20 43 07](https://user-images.githubusercontent.com/1174328/209224054-dd480f32-e971-473a-ac23-add631bda41a.png)

![Screenshot 2022-12-22 at 20 43 45](https://user-images.githubusercontent.com/1174328/209224123-08ae493b-dc35-4516-b0f4-ea9dad89f8c1.png)

### Option B: Compile the workflow from scratch on your own machine.

This one is a bit more involved, but all you have to do is.

```bash
# install the Dart SDK
brew tap dart-lang/dart
brew install dart

# clone the repo
git clone https://github.com/techouse/alfred-tailwindcss-docs
cd alfred-tailwindcss-docs

# edit the env
cp .env.example .env
vim .env

# generate all the environment-dependent files
make code_gen

# compile the app
make compile
```

**Comment by techouse** [comment]
I'll add a wrapper script to detect the architecture and run it as required.

**Comment by techouse** [comment]
Right, `v2.1.10` is now executed as

```bash
arch -86_64 ./docs -q "{query}"
```

That should force the OS to run it as such.
